/**
 * Lo que dicen los vecinos de la ciudad al tocarlos en el mapa: 50 frases
 * buenas y 50 malas. Cuanto mejor va la ciudad (popularidad del alcalde,
 * barrios renovados, grandes obras), más probable es una buena.
 */
export const GOOD_LINES: readonly string[] = [
  '¡Es el mejor alcalde que hemos tenido!',
  'Por fin han arreglado los baches de mi calle.',
  'Las calles están más limpias que nunca.',
  'El metro ya llega puntual, ¡quién lo diría!',
  'Me encanta este barrio, hay vida a todas horas.',
  'Han puesto farolas nuevas: ya no da miedo volver de noche.',
  'El parque está precioso esta temporada.',
  'Abrieron una biblioteca nueva al lado de casa.',
  'Mi hijo ya tiene plaza en la escuela del barrio.',
  'Los basureros pasan todos los días. ¡Un lujo!',
  'Nueva York es la mejor ciudad del mundo.',
  'He encontrado trabajo en las obras del ayuntamiento.',
  'Los alquileres por fin se han calmado un poco.',
  'Hay más policía de barrio y se nota.',
  '¡Qué bonito ha quedado Times Square!',
  'Los bomberos llegaron en tres minutos. ¡Héroes!',
  'Mi negocio va mejor que nunca este año.',
  'Ya puedo cruzar el puente en bici sin miedo.',
  'Han pintado los murales del barrio. ¡Arte puro!',
  'Esta ciudad acoge a todo el mundo, como a mí.',
  'El aire huele mejor desde que limpiaron el río.',
  'Los perritos calientes de la esquina son gloria.',
  'Ayer hubo concierto gratis en el parque.',
  'Me siento seguro paseando con mi perro.',
  'El hospital nuevo atiende rapidísimo.',
  'Mis vecinos son como una familia.',
  'Han abierto un mercado con fruta fresca.',
  'El autobús nuevo tiene hasta calefacción.',
  'Las escuelas tienen ordenadores nuevos. ¡El futuro!',
  'Los turistas vuelven a llenar las tiendas.',
  'He votado al alcalde y lo volvería a votar.',
  'Ya no hay grafitis en el vagón de mi línea.',
  'El ayuntamiento escucha a los vecinos, por fin.',
  'Se respira optimismo en las calles.',
  'Mi abuela dice que la ciudad está como en sus buenos años.',
  'Los domingos el rastro de Brooklyn es una fiesta.',
  'Hay trabajo para quien lo busca.',
  'Han plantado árboles en mi avenida.',
  'El diner de la esquina sirve el mejor café.',
  'Los niños vuelven a jugar en la calle.',
  'El puerto da empleo a medio barrio.',
  '¡Esta ciudad nunca duerme y me encanta!',
  'Los semáforos nuevos van de maravilla.',
  'Han reabierto el cine de mi barrio.',
  'Los impuestos se notan: todo está más cuidado.',
  'El alcalde vino a saludarnos en persona.',
  'Hay música en cada esquina.',
  'Mi calle ha ganado el premio a la más limpia.',
  'Vine con una maleta y ahora tengo mi casa aquí.',
  'Pixelopolis brilla más que nunca. ¡Qué orgullo!',
];

export const BAD_LINES: readonly string[] = [
  'Los cubos de basura están llenos desde hace días.',
  'Las calles están muy sucias.',
  'Hay baches por todas partes, me he roto un tobillo.',
  'El metro lleva veinte minutos de retraso. Otra vez.',
  'Los alquileres están por las nubes.',
  'De noche no se puede andar tranquilo por aquí.',
  'Me han robado la bici. Es la tercera este año.',
  'Hay ratas del tamaño de un gato en el parque.',
  'El alcalde no se entera de nada.',
  'Las farolas de mi calle llevan un mes fundidas.',
  'Los grafitis cubren hasta las ventanas.',
  'No hay trabajo para los jóvenes.',
  'El agua del grifo sale marrón.',
  'Huele fatal desde que hay huelga de basureros.',
  'El autobús nunca pasa a su hora.',
  'Los impuestos suben y no veo nada a cambio.',
  'Han cerrado la escuela de mi hijo.',
  'El hospital tiene listas de espera eternas.',
  'Hay atascos a todas horas en la avenida.',
  'El río está lleno de porquería.',
  'Los políticos solo vienen cuando hay elecciones.',
  'Mi casero no arregla la calefacción.',
  'Han subido el billete del metro otra vez.',
  'Hay más coches que personas en esta ciudad.',
  'Los parques están abandonados.',
  'Las sirenas no me dejan dormir.',
  'Cerraron la fábrica y se quedaron sin trabajo cien vecinos.',
  'Los turistas lo llenan todo y los precios suben.',
  'El puente necesita una reparación urgente.',
  'Los niños no tienen dónde jugar.',
  'Las aceras están rotas, cuidado con caerse.',
  'Este alcalde solo piensa en salir en la tele.',
  'Hay mendigos en cada esquina y nadie hace nada.',
  'Las obras de mi calle no se acaban nunca.',
  'Nadie recoge las hojas ni la nieve.',
  'Mi negocio está cerrando por los impuestos.',
  'Los semáforos de mi cruce están estropeados.',
  'La policía tarda una hora en venir.',
  'Hay humo de las fábricas todo el día.',
  'El ruido de la ciudad me vuelve loco.',
  'No hay bancos para sentarse en todo el barrio.',
  'Me pusieron una multa por aparcar en mi propia puerta.',
  'Las bibliotecas cierran a las cinco. ¿Para qué?',
  'Los precios del súper son un robo.',
  'Se han llevado el mercado del barrio.',
  'Esta ciudad era mejor hace diez años.',
  'Hay jeringuillas en el parque infantil.',
  'Los inspectores solo multan al pequeño comercio.',
  'Las promesas del ayuntamiento se las lleva el viento.',
  'Pixelopolis se cae a pedazos y nadie hace nada.',
];

/** Una frase de un vecino; `mood` de 0 (la ciudad va fatal) a 1 (va de maravilla). */
export function citizenLine(mood: number, rand: () => number = Math.random): { text: string; good: boolean } {
  const good = rand() < 0.15 + Math.max(0, Math.min(1, mood)) * 0.7;
  const list = good ? GOOD_LINES : BAD_LINES;
  return { text: list[Math.floor(rand() * list.length)], good };
}
